default_stages: [pre-commit]
fail_fast: true

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-json
  - id: pretty-format-json
    args: [--autofix]
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: no-commit-to-branch
    args: [--branch, main]
  - id: trailing-whitespace
  - id: check-case-conflict
  - id: check-xml
  - id: fix-byte-order-marker

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v3.4.0
  hooks:
  - id: conventional-pre-commit
    stages: [commit-msg]
    args: []

- repo: local
  hooks:
  - id: coding-standard
    name: Coding standards
    language: system
    entry: vendor/bin/phpcs --standard=PSR12 ./src ./tests
    always_run: true

  - id: static-analysis
    name: Static analysis
    language: system
    entry: vendor/bin/phpstan analyse ./src ./tests --level=max
    pass_filenames: false

  - id: php-unit
    name: PHPUnit tests
    language: system
    entry: vendor/bin/phpunit
    pass_filenames: false
