services:

  db:
    image: mariadb:11.5
    env_file:
    - .env
    ports:
    - 3306:3306
    volumes:
    - db-data:/var/lib/mysql

  app:
    image: mcr.microsoft.com/devcontainers/php:1-8.2-bullseye
    depends_on:
    - db
    volumes:
    - ..:/workspace:cached

volumes:
  db-data:
